name: Scrape latest entertainment_and_arts RSS

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install xsltproc
      run: sudo apt-get install xsltproc
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest entertainment_and_arts RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml > entertainment_and_arts.xml
    - name: Run XSLT
      run: |-
        xsltproc rss.xslt entertainment_and_arts.xml > entertainment_and_arts.md
    - name: Run XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt entertainment_and_arts.xml > entertainment_and_arts_nodate.md
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest entertainment_and_arts RSS: ${timestamp}" || exit 0
        git push
