name: Scrape latest home UK RSS

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install xsltproc
      run: sudo apt-get install xsltproc
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest UK RSS
      run: |-
        curl https://feeds.bbci.co.uk/news/rss.xml?edition=uk > home_uk.xml
    - name: Run XSLT
      run: |-
        xsltproc rss.xslt home_uk.xml > home_uk.md
    - name: Run XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt home_uk.xml > home_uk_nodate.md
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest home UK RSS: ${timestamp}" || exit 0
        git push
