name: Scrape latest politics RSS

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install xsltproc
      run: sudo apt-get install xsltproc
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest politics RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/politics/rss.xml > politics.xml
    - name: Run XSLT
      run: |-
        xsltproc rss.xslt politics.xml > politics.md
    - name: Run XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt politics.xml > politics_nodate.md
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest politics RSS: ${timestamp}" || exit 0
        git push
