name: Scrape latest RSS

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install xsltproc
      run: sudo apt-get install xsltproc
    - name: Check out this repo
      uses: actions/checkout@v2
    

    # Fetch RSS
    - name: Fetch latest UK RSS
      run: |-
        curl https://feeds.bbci.co.uk/news/rss.xml?edition=uk > home_uk.xml
    - name: Fetch latest business RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/business/rss.xml > business.xml
    - name: Fetch latest education RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/education/rss.xml > education.xml
    - name: Fetch latest entertainment_and_arts RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml > entertainment_and_arts.xml
    - name: Fetch latest health RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/health/rss.xml > health.xml
    - name: Fetch latest politics RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/politics/rss.xml > politics.xml
    - name: Fetch latest science_and_environment RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/science_and_environment/rss.xml > science_and_environment.xml
    - name: Fetch latest technology RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/technology/rss.xml > technology.xml
    - name: Fetch latest world RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/world/rss.xml > world.xml
    - name: Fetch latest world/africa RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/world/africa/rss.xml > world_africa.xml
    - name: Fetch latest world/asia RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/world/asia/rss.xml > world_asia.xml
    - name: Fetch latest world/europe RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/world/europe/rss.xml > world_europe.xml
    - name: Fetch latest world/latin_america RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/world/latin_america/rss.xml > world_latin_america.xml
    - name: Fetch latest world/middle_east RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/world/middle_east/rss.xml > world_middle_east.xml
    - name: Fetch latest world/us_and_canada RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml > world_us_and_canada.xml
    - name: Fetch latest england RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/england/rss.xml > england.xml
    - name: Fetch latest northern_ireland RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/northern_ireland/rss.xml > northern_ireland.xml
    - name: Fetch latest scotland RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/scotland/rss.xml > scotland.xml
    - name: Fetch latest wales RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/wales/rss.xml > wales.xml


    # Transform
    - name: Run home UK XSLT
      run: |-
        xsltproc rss.xslt home_uk.xml > home_uk.md
    - name: Run home UK XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt home_uk.xml > home_uk_nodate.md

    - name: Run business XSLT
      run: |-
        xsltproc rss.xslt business.xml > business.md
    - name: Run business XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt business.xml > business_nodate.md

    - name: Run education XSLT
      run: |-
        xsltproc rss.xslt education.xml > education.md
    - name: Run education XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt education.xml > education_nodate.md

    - name: Run entertainment_and_arts XSLT
      run: |-
        xsltproc rss.xslt entertainment_and_arts.xml > entertainment_and_arts.md
    - name: Run entertainment_and_arts XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt entertainment_and_arts.xml > entertainment_and_arts_nodate.md      

    - name: Run health XSLT
      run: |-
        xsltproc rss.xslt health.xml > health.md
    - name: Run entertainment_and_arts XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt health.xml > health_nodate.md     

    - name: Run politics XSLT
      run: |-
        xsltproc rss.xslt politics.xml > politics.md
    - name: Run politics XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt politics.xml > politics_nodate.md   

    - name: Run science_and_environment XSLT
      run: |-
        xsltproc rss.xslt science_and_environment.xml > science_and_environment.md
    - name: Run science_and_environment XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt science_and_environment.xml > science_and_environment_nodate.md   

    - name: Run technology XSLT
      run: |-
        xsltproc rss.xslt technology.xml > technology.md
    - name: Run technology XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt technology.xml > technology_nodate.md   

    - name: Run world XSLT
      run: |-
        xsltproc rss.xslt world.xml > world.md
    - name: Run world XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt world.xml > world_nodate.md   

    - name: Run world/africa XSLT
      run: |-
        xsltproc rss.xslt world_africa.xml > world_africa.md
    - name: Run world/africa XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt world_africa.xml > world_africa_nodate.md   

    - name: Run world/asia XSLT
      run: |-
        xsltproc rss.xslt world_asia.xml > world_asia.md
    - name: Run world/asia XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt world_asia.xml > world_asia_nodate.md   

    - name: Run world/europe XSLT
      run: |-
        xsltproc rss.xslt world_europe.xml > world_europe.md
    - name: Run world/europe XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt world_europe.xml > world_europe_nodate.md

    - name: Run world/latin_america XSLT
      run: |-
        xsltproc rss.xslt world_latin_america.xml > world_latin_america.md
    - name: Run world/latin_america XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt world_latin_america.xml > world_latin_america_nodate.md   

    - name: Run world/middle_east XSLT
      run: |-
        xsltproc rss.xslt world_middle_east.xml > world_middle_east.md
    - name: Run world/middle_east XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt world_middle_east.xml > world_middle_east_nodate.md   

    - name: Run world/us_and_canada XSLT
      run: |-
        xsltproc rss.xslt world_us_and_canada.xml > world_us_and_canada.md
    - name: Run world/us_and_canada XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt world_us_and_canada.xml > world_us_and_canada_nodate.md   

    - name: Run england XSLT
      run: |-
        xsltproc rss.xslt england.xml > england.md
    - name: Run england XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt england.xml > england_nodate.md   

    - name: Run northern_ireland XSLT
      run: |-
        xsltproc rss.xslt northern_ireland.xml > northern_ireland.md
    - name: Run northern_ireland XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt northern_ireland.xml > northern_ireland_nodate.md  

    - name: Run scotland XSLT
      run: |-
        xsltproc rss.xslt scotland.xml > scotland.md
    - name: Run scotland XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt scotland.xml > scotland_nodate.md  

    - name: Run wales XSLT
      run: |-
        xsltproc rss.xslt wales.xml > wales.md
    - name: Run wales XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt wales.xml > wales_nodate.md  



    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest RSS: ${timestamp}" || exit 0
        git push
