name: Scrape latest RSS

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest JSON data
      run: |-
        curl https://feeds.bbci.co.uk/news/rss.xml > home_rss.xml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest RSS: ${timestamp}" || exit 0
        git push
