name: Scrape latest science_and_environment RSS

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install xsltproc
      run: sudo apt-get install xsltproc
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest science_and_environment RSS
      run: |-
        curl http://feeds.bbci.co.uk/news/science_and_environment/rss.xml > science_and_environment.xml
    - name: Run XSLT
      run: |-
        xsltproc rss.xslt science_and_environment.xml > science_and_environment.md
    - name: Run XSLT (no date)
      run: |-
        xsltproc rss_nodate.xslt science_and_environment.xml > science_and_environment_nodate.md
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest science_and_environment RSS: ${timestamp}" || exit 0
        git push
